---
name: Snapmaker Monitor
version: dev
slug: snapmaker-monitor
description: Python script to monitor Snapmaker 2.0 printer status and send updates to Home Assistant.
url: https://github.com/NRE-Com-Net/hassio-addon-snapmaker-monitor
codenotary: nemesissre@gmail.com
boot: manual_only
homeassistant_api: true
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  ha_token: ""
  ha_webhook_url: ""
  sm_ip: null
  sm_port: 8080
  log_level: info
  mqtt_broker: ""
  mqtt_port: 1883
  mqtt_topic: snapmaker/status
  mqtt_user: ""
  mqtt_password: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ha_token: str?
  ha_webhook_url: str?
  sm_ip: str
  sm_port: int(1,65535)?
  mqtt_broker: str?
  mqtt_port: int(1,65535)?
  mqtt_topic: str?
  mqtt_user: str?
  mqtt_password: str?
